name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['AnthropicIntegration']
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build ${{ matrix.project }}
      run: |
        cd ${{ matrix.project }}
        go build -v ./...

    - name: Test ${{ matrix.project }}
      run: |
        cd ${{ matrix.project }}
        go test -v ./...
